[project]
name = "mysecondagentapplication"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai-agent>=0.1.0",
    "python-dotenv>=1.1.1",
    "vectorize-client>=0.0.0",
]
